name: Build and Publish Image
on:
  push:
    branches: [ main ] # mainブランチが更新されたら発動
jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # これが Pelican に貼り付ける住所になる
          tags: ghcr.io/${{ github.repository }}:latest
